name: Build

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 14
        check-latest: true
    - name: Install Node modules
      run: npm build
    - uses: TheDoctor0/zip-release@0.4.2
      with:
        filename: "build.zip"
        path: build
    - name: Zip build
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_name: build.zip
        asset_path: ./build.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
